# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AuxTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(925, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plus_5_deg_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plus_5_deg_button.sizePolicy().hasHeightForWidth())
        self.plus_5_deg_button.setSizePolicy(sizePolicy)
        self.plus_5_deg_button.setObjectName("plus_5_deg_button")
        self.gridLayout.addWidget(self.plus_5_deg_button, 1, 0, 1, 1)
        self.laser_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laser_button.sizePolicy().hasHeightForWidth())
        self.laser_button.setSizePolicy(sizePolicy)
        self.laser_button.setMinimumSize(QtCore.QSize(0, 17))
        self.laser_button.setCheckable(True)
        self.laser_button.setObjectName("laser_button")
        self.gridLayout.addWidget(self.laser_button, 0, 2, 1, 1)
        self.air_out_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air_out_button.sizePolicy().hasHeightForWidth())
        self.air_out_button.setSizePolicy(sizePolicy)
        self.air_out_button.setCheckable(True)
        self.air_out_button.setObjectName("air_out_button")
        self.gridLayout.addWidget(self.air_out_button, 0, 1, 1, 1)
        self.disco_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disco_button.sizePolicy().hasHeightForWidth())
        self.disco_button.setSizePolicy(sizePolicy)
        self.disco_button.setCheckable(True)
        self.disco_button.setObjectName("disco_button")
        self.gridLayout.addWidget(self.disco_button, 1, 2, 1, 1)
        self.air_in_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air_in_button.sizePolicy().hasHeightForWidth())
        self.air_in_button.setSizePolicy(sizePolicy)
        self.air_in_button.setMinimumSize(QtCore.QSize(302, 17))
        self.air_in_button.setCheckable(True)
        self.air_in_button.setChecked(False)
        self.air_in_button.setObjectName("air_in_button")
        self.gridLayout.addWidget(self.air_in_button, 0, 0, 1, 1)
        self.minus_5_deg_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minus_5_deg_button.sizePolicy().hasHeightForWidth())
        self.minus_5_deg_button.setSizePolicy(sizePolicy)
        self.minus_5_deg_button.setObjectName("minus_5_deg_button")
        self.gridLayout.addWidget(self.minus_5_deg_button, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 18))
        self.menubar.setObjectName("menubar")
        self.menuAUX_TEST = QtWidgets.QMenu(self.menubar)
        self.menuAUX_TEST.setObjectName("menuAUX_TEST")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAUX_TEST.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plus_5_deg_button.setText(_translate("MainWindow", "+5 deg"))
        self.laser_button.setText(_translate("MainWindow", "Laser On"))
        self.air_out_button.setText(_translate("MainWindow", "Air Out"))
        self.disco_button.setText(_translate("MainWindow", "WEEEEEEEE"))
        self.air_in_button.setText(_translate("MainWindow", "Air In"))
        self.minus_5_deg_button.setText(_translate("MainWindow", "-5 deg"))
        self.menuAUX_TEST.setTitle(_translate("MainWindow", "AUX TEST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
